### ISSUE TITLE
Отредактировать manifest и добавить зависимости в gradle

### ISSUE THREAD

**Issue by CNJerry-IvanovVyacheslav** [andrei-urich/practicum-android-diploma#2]

**Comment by andrei-urich** [comment]
Настройки build.gradle файлов и AndroidManifest.xml (минимально поддерживаемая версия Android, ориентация экрана приложения, ссылка на класс Application и основную тему, подключить библиотеки (Retrofit, koin, fragments, room, gson, glide, kapt)
